spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: authwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwtauthwithjwt
  refresh-token-validity-in-seconds: 1209600
  access-token-validity-in-seconds: 43200